spring:
  application:
    name: dubbo-privider-app
dubbo:
  application:
    name: dubbo-privider-consumer
  registry:
    #address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2180,127.0.0.1:2182
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
server:
  port: 8082
  servlet:
    context-path: /consumer